language: node_js
cache:
  directories
    - node_modules
    - ~/.npm

node_js:
  - '12'
git:
  depth: 3

script:
  - yarn test
notifications:
  slack: movicaremx:FdziNfqxPS0SXgKzNHDdA9mn
  email:
    recipients:
      - garpzos2001@gmail.com
    on_success: always
    on_failure: always

deploy:
  provide: heroku
  cleanup: true
  keep-history: true
  api_key: apikey
  app: platzi-backend
  on:
    repo: Arcani18/platzi-store-backend
